## YAML Template.
---
spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres    
    password: postgres 
  jpa:
    hibernate.ddl-auto: create-drop
    generate-ddl: true
    show-sql: true  
    hibernate:
      ddl-auto: create-drop
    
server:
    port: 9080
    servlet:
        context-path: /parqueadero
        
logging:
   level: 
      # Hides HHH000424: Disabling contextual LOB creation as createClob() method threw error 
      org.hibernate.engine.jdbc.env.internal.LobCreatorBuilderImpl: WARN  